version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./backend/mysql.Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    networks:
      - my_network
    volumes:
      - db_data2:/var/lib/mysql
    restart: always

  php:
    build:
      context: .
      dockerfile: ./frontend/php.Dockerfile   
    networks:
      - my_network
    ports:
      - "93:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database  
    volumes:
      - ./frontend/default:/etc/php/sites-available/default
      - ./frontend/src:/var/www/html
    depends_on:
      - db
    restart: always
     
networks:
  my_network:
    driver: bridge

volumes:
  db_data2:
